### ISSUE TITLE
Authorization Sever Spec updates

### ISSUE THREAD

**Issue by sabineschaller** [interledger/open-payments#103]
* limits in access objects mirror incoming and outgoing payment data model, respectively
  * remove `interval` property
* `startsAt` follows [ISO 8601 Repeating intervals](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals)
* point out that all amounts are maxima, i.e. it is possible to  create many payments until the total equals the granted amount

**Comment by wilsonianb** [comment]
I was thinking it would be `interval` (outside of `limits`) as [ISO 8601 Repeating intervals](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals)

**Comment by sabineschaller** [comment]
Can we get rid of `expiresAt` this way, too, and just have `interval`?
* one-time grant: R0/2022-04-14T13:00:00Z/P1M` - starts at `2022-04-14T13:00:00Z`, doesn't repeat, i.e. expires at `2022-05-14T13:00:00Z`
* recurring grant: `R5/2022-04-14T13:00:00Z/P1M` - starts at `2022-04-14T13:00:00Z`, repeats 5 times, i.e. expires at `2022-10-14T13:00:00Z`

**Comment by wilsonianb** [comment]
:+1: Yeah, I think `expiresAt` is only relevant if there's an interval, so it can just be included in the new repeating `interval` format
