### ISSUE TITLE
Open Payment Spec update: * remove `state` in incoming and outgoing payments

### ISSUE THREAD

**Issue by sabineschaller** [interledger/open-payments#104]
* incoming payment: 
  * add `completed` flag
  * payment is expired if `completed=false` and `now>expiresAt`
  * if payment is not complete and not expired, it is `pending`
* outgoing payment: 
  * add `failed` flag
  * payment is complete if `sendAmount=sentAmount`
  * if payment has not failed and `sendAmount!=sentAmount`, payment is `pending`
 
@wilsonianb lmk if I summarized that correctly

**Comment by wilsonianb** [comment]
>payment is complete if sendAmount=sentAmount

With quote amounts being fixed, outgoing payments are fixed-receive. So when sending completes, `sentAmount` is `<=sendAmount`. If the leftover payment balance from `sendAmount` is handled asynchronously (such as Rafiki's current [`outgoing_payment.completed`](https://github.com/interledger/rafiki/blob/main/docs/transaction-api.md#payment-resolution) webhook event), the outgoing payment wouldn't be technically be complete yet (`sentAmount < sendAmount`).
I'm wondering if either we need a `completed` flag (in addition to `failed`...) or we still have `state` (`pending`, `completed`, `failed`). Rafiki's implementation will need one of those two options internally.

**Comment by wilsonianb** [comment]
:thinking: OTOH, would we every want to return an outgoing payment as `completed` (via either flag or `state`) with `sentAmount`<`sendAmount` (due to unresolved leftover balance)? Would an implementation always just return `sentAmount` as `sendAmount`? In which case `payment is complete if sendAmount=sentAmount` would still suffice.

**Comment by wilsonianb** [comment]
>* incoming payment: 
>   * add `completed` flag

I keep thinking back to the idea of completing an incoming payment by making `incomingAmount` equal `receivedAmount`.
It would make it consistent with outgoing payments:
>payment is complete if sendAmount=sentAmount

I think there were concerns about knowing the precise `receivedAmount` value to use in the `PUT`. What' if it were instead `POST /{id}/complete`?

**Comment by sabineschaller** [comment]
> I keep thinking back to the idea of completing an incoming payment by making `incomingAmount` equal `receivedAmount`.

But `incomingAmount` is optional.

> I think there were concerns about knowing the precise `receivedAmount` value to use in the PUT request body. What' if it were instead `POST /{id}/complete`?

The PUT only takes `completed: true` as body parameter. Which `receivedAmount` are you referring to?
I'm happy with `/{id}/complete` but why not `PUT /{id}/complete`?

**Comment by wilsonianb** [comment]
The original idea was do `PUT /{id}` and specify `incomingAmount` in the body.
If the `incomingAmount` matched `receivedAmount`, the incoming payment would be completed.
But that created a race condition of using a queried `receivedAmount` value in the request and the incoming payment receiving additional amounts.

I'm suggesting `POST /{id}/complete` without a body.

>I'm happy with /{id}/complete but why not PUT /{id}/complete

I'm having trouble finding examples ([`POST /introspect`](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-resource-servers#section-3.3)?), but I feel like `POST`ing to a url ending in a verb/action is common.

**Comment by sabineschaller** [comment]
> The original idea was do PUT /{id} and specify `incomingAmount` in the body.

Tbh, I don't remember that. But we had so many ideas...

I searched for [difference between POST and PUT](https://restfulapi.net/rest-put-vs-post/), and it seems like we should use PATCH :laughing:

**Comment by wilsonianb** [comment]
I agree `PATCH` is preferable to `PUT` for completing an incoming payment.

I think `POST /{id}/complete` would be described as RPC:

> In a REST API, you already have `GET /trips` and `POST /trips`, so a lot of people would try to use endpoints that look a bit like sub-resources for these actions:
> - `POST /trips/123/start`
> - `POST /trips/123/finish`
> - `POST /trips/123/cancel`
>
>This is basically jamming RPC-style endpoints into a REST API, which is certainly a popular solution but is technically not REST. 

https://www.smashingmagazine.com/2016/09/understanding-rest-and-rpc-for-http-apis/

:point_up_2: That goes on to suggest having a `status` (`state`) field that can be `PATCH`ed...
