### ISSUE TITLE
Separate spec for RS<>AS API

### ISSUE THREAD

**Issue by wilsonianb** [interledger/open-payments#123]
Should the [`/introspect` endpoint](https://github.com/interledger/open-payments/blob/master/auth-server-open-api-spec.yaml#L349) be moved to its own OpenAPI spec, so that [client<>AS](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.2.1) and [RS<>AS](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-resource-servers) GNAP interactions are represented in distinct specs?

**Comment by sabineschaller** [comment]
We came around and now want to split the spec into the following components:
- Client <> AS
- RS <> AS
- AS <> IDP

**Comment by adrianhopebailie** [comment]
We should split these into two groups: Open Payments and Rafiki
The Open Payments APIs are:
- client <> AS
- client <> RS

The Rafiki APIs are:
- AS <> IDP
- RS <> AS
