### ISSUE TITLE
Session Currency

### ISSUE THREAD

**Issue by matdehaast** [interledger/open-payments#13]
We need to work out the mechanisms with which the third-party doing spends against sessions is able to know and support the underlaying currency of the session

**Comment by sharafian** [comment]
My suggestion would be that the sessions use an agreement currency that can be specified at the time of session creation. Although that raises some problems for a session that was created automatically. Another option would be to specify a currency when you request the balance and get it converted on the fly, but then you get some weird artifacts when the exchange rate fluctuates between the requested currency and the currency that the session is stored as

as usual currency adds a whole level of complexity :)

I think the one thing is that a site should never need to be aware of every user's currency. I'm more OK with having a list of currencies that wallets should generally support expressing amounts in
