### ISSUE TITLE
Add use cases to openpayments.dev

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/open-payments#170]

**Comment by AlexLakatos** [comment]
Add use cases to the "Guides" section:
- peer-to-peer transfer
- e-commerce platforms
- recurring payments
- web monetization

**Comment by melissahenderson** [comment]
Addtl note to say we have the guide for Make Recurring Payments

**Comment by melissahenderson** [comment]
Related PR https://github.com/interledger/open-payments/pull/524

**Comment by melissahenderson** [comment]
PR was merged today. Closing this issue.
