### ISSUE TITLE
Design system for Client Registration

### ISSUE THREAD

**Issue by sappenin** [interledger/open-payments#20]
Consider OAuth dynamic client registration. Also, consider a merchant registry of some sort that might be able to vouch for merchants for the community.

Another idea here is that we might be able to use the PKI infrastructure being created for routing updates here.

**Comment by matdehaast** [comment]
Thanks for adding this @sappenin. Also want to add in the work that openid using a federated model. https://openid.net/specs/openid-connect-federation-1_0-ID2.html

**Comment by sappenin** [comment]
From the ILP community call, it looks like this proposal ([oauth.xyz](https://oauth.xyz/)) might align better with the security model of OpenPayments.
