### ISSUE TITLE
Deprecate `description` and `externalRef` in favor of `metadata`

### ISSUE THREAD

**Issue by sabineschaller** [interledger/open-payments#221]
In some use cases, `description` and `externalRef` are overkill, where in others, it may not be enough. I vote for using `metadata` instead. Making it type `string` and stringify everything would probably be easiest.

**Comment by wilsonianb** [comment]
Or memos :stuck_out_tongue_winking_eye: 
https://xrpl.org/transaction-common-fields.html#memos-field

**Comment by adrianhopebailie** [comment]
Memos seems like a nice way to have SOME structure.
Basically an array of objects with a rel, type, and value.
(Odd that memos in XRPL use `format` for the `mime-type`)

Format can default to `text/plain`

```json
{
  "memos": [
    {
      "rel": "invoiceNumber",
      "value": "INV542654"
    },
    {
      "rel": "description",
      "value": "Payment for the widgets"
    },
    {
      "rel": "invoice",
      "type": "application/pdf"
      "value": "<base64encoded PDF>"
    } 
  ]
}
