### ISSUE TITLE
Duplicated info for different endpoints

### ISSUE THREAD

**Issue by austin-king** [interledger/open-payments#24]
As I was reading the docs I noticed that the same description:
URL of the server's sessions endpoint where the client is able to create new sessions with the subject.

exists for three variables: authorization_issuer, authorization_endpoint, token_endpoint

I would just fix and make a PR but I don't know exactly what each of these values is supposed to represent

**Comment by matdehaast** [comment]
@austin-king think this will be addressed with the new stuff Adrian has in https://github.com/interledger/open-payments/pull/32 
Thanks for the feedback. 

Those are to do with the oAuth2 server (AS) in the interaction. Those flows aren't fully defined yet and part of what we are working on next with identity.
