### ISSUE TITLE
HTTP signature docs

### ISSUE THREAD

**Issue by tselit** [interledger/open-payments#321]
Provide comprehensive documentation about the need and use of HTTP signatures in the Open Payments API, and as part of grant negotiation.

**Comment by melissahenderson** [comment]
New path is /introduction/http-signatures/

**Comment by melissahenderson** [comment]
Related #383

**Comment by melissahenderson** [comment]
I'm going to work on merging the updates in 383 this week and am closing this issue as Completed.
