### ISSUE TITLE
Add `receiverWalletAddress` to `POST /quote` request body

### ISSUE THREAD

**Issue by njlie** [interledger/open-payments#344]
In order for a quote to be created, the receiver's wallet address should be made available to the endpoint in the request body since it is no longer part of the `receiver` url.

**Comment by sabineschaller** [comment]
I don't think this is what we want. We should rather return the auth server url with a 401 response, i.e. we try creating a quote without a grant and if that comes back with a 401, it returns the auth server url.

**Comment by njlie** [comment]
Closing as no longer planned.
