### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by matdehaast** [interledger/open-payments#4]
### Issuer Ambiguity
In the https://github.com/adrianhopebailie/open-payments#discovery section there is a mention of the wallet being the `issuer` of  payment pointer. Then under the `well-known` response there is an `issuer` from oAuth 2 spec. This issuer refers to the authorization `issuer`. We need to clear up the ambiguity is it can be confusing

### Discovery URL's ( https://github.com/adrianhopebailie/open-payments#discovery)
The server location is referenced as `wallet.example` but the response to the `well-known` references `server.wallet.example`. I think these should be the same

### Discrepancy of `well-known`
There is a mismatched between the `well-known` endpoints of the discovery and https://github.com/adrianhopebailie/open-payments#use-case-web-monetization

**Comment by adrianhopebailie** [comment]
> Then under the well-known response there is an issuer from oAuth 2 spec. This issuer refers to the authorization issuer. We need to clear up the ambiguity is it can be confusing

Are these different?
