### ISSUE TITLE
Decide how where Account URLs live

### ISSUE THREAD

**Issue by sappenin** [interledger/open-payments#40]
See discussion thread here: https://github.com/interledger/open-payments/pull/32#discussion_r428363616

**Comment by adrianhopebailie** [comment]
@sappenin picking up from #32 I think we resolved this on the community call.

I believe we agreed that the Payment Pointer always resolves to a URL that is the account resource and that a server that wishes to have admin APIs for accounts at a different URL that is orthogonal.

If that's correct can we close this?

**Comment by sappenin** [comment]
@adrianhopebailie yes, that's my understanding. Closing this as resolved.
