### ISSUE TITLE
Note that invoices may require small overpayment

### ISSUE THREAD

**Issue by kincaidoneil** [interledger/open-payments#41]
If the exchange rate is positive, e.g. 1 unit of the source asset delivers 500 destination units, it may be impossible to delivery the precise invoice amount. Thus, the receiver should allow at least some percentage above the invoice amount to be fulfilled at the STREAM layer.

**Comment by matdehaast** [comment]
@kincaidoneil It should be possible at the STREAM library level to actually workout and set this overpayment  threshold/amount?

**Comment by kincaidoneil** [comment]
On the sender side, yes. `@interledger/pay` increases the `maxSourceAmount` by 1 source unit to compensate for any overpayment. Then, if necessary on the final packet, it'll reduce the min destination amount (below the minimum exchange rate) by that 1 source unit converted into destination units.

But on the receiver side, if you wanted to precisely set the destination amount, you'd need to know both the sender's asset (which isn't always shared) and the exchange rate between your two assets. It'd be simpler to just say, invoice is for `x` amount, but the implementation allows receiving `x` + up to 1% more
