### ISSUE TITLE
Update 'Make a one-time payment` guide

### ISSUE THREAD

**Issue by melissahenderson** [interledger/open-payments#410]
Based on Sabine and Alex's feedback about the Open Payments guides (~ end of November 2023), the One-Time Payment guide should be updated as follows:

- [x] Include the http-msg-sig-note.mdx as a partial under Dependencies
- [x] Use tabbed displays for code snippets and API calls
- [x] Import existing TS code snippets rather than hardcoding on the page 
- [x] Include the TS prerequisites in the tab
- [x] Explain any relevant/important/required API properties
- [x] In step 8, use a Starlight aside rather than Note:

See https://openpayments.guide/guides/create-interactive-grant/ for usage examples.

**Comment by hajjimo** [comment]
Issue linked to PR #432, which has been merged into main
