### ISSUE TITLE
 Update 'Make a recurring payment` guide

### ISSUE THREAD

**Issue by melissahenderson** [interledger/open-payments#411]
Based on Sabine and Alex's feedback about the Open Payments guides (~ end of November 2023), the Recurring Payment guide should be updated as follows:

- [x] First, steps 1 - 7 are the same as steps 1 - 7 in the one-time payment guide. Whichever guide you work on first, you should be able to copy/paste from one guide to the other. **Exception:** In the example in Step 5, the `metadata description` reads `one time payment example`, which isn't accurate for the recurring payment guide. I suggest changing the description so the same example can be used in both guides.
- [x] Include the http-msg-sig-note.mdx as a partial under Dependencies
- [x] Use tabbed displays for code snippets and API calls
- [x] Import existing TS code snippets rather than hardcoding on the page 
- [x] Include the TS prerequisites in the tab
- [x] Explain any relevant/important/required API properties
- [x] In step 8, use a Starlight aside rather than Note:

See https://openpayments.guide/guides/create-interactive-grant/ for examples.

**Comment by hajjimo** [comment]
Issue is linked to PR #444, which has been merged into main.
