### ISSUE TITLE
Backwards compatibility in payment details

### ISSUE THREAD

**Issue by sharafian** [interledger/open-payments#50]
https://github.com/interledger/open-payments/blob/master/documentation/docs/accounts.mdx#payment-details

This came up in a discussion today which prompted me to file this issue. Why is the payment details response not backwards compatible with the SPSP response? We could support existing SPSP clients with no changes by keeping the same content type and the same destination_account and shared_secret, and just add open-payments fields additively. While I understand there's a workable migration path it seems that just making the response body backwards compatible would be simpler

**Comment by adrianhopebailie** [comment]
The current proposal is backwards compatible using the content-type as a way to disambiguate between SPSP and Open Payments.

This takes advantage of the fact that SPSP explicitly uses a non-standard content-type allowing open payments to define responses for content types such as `application/json` and `text/html` without breaking existing SPSP clients.

The same data is returned but using a different JSON schema for Open Payments based on camel case and use more appropriate property names.

<table>
<tr>
	<td>
	<td>SPSP
	<td>Open Payments
<tr>
	<td>Content Type
	<td>`application/spsp4+json`
	<td>`application/ilp-stream+json`
<tr>
	<td>Destination ILP Address
	<td>`destination_account`
	<td>`ilpAddress`
<tr>
	<td>Shared Secret
	<td>`shared_secret`
	<td>`sharedSecret`
</table>

Open Payments servers SHOULD support both content types for now but clients SHOULD move to Open Payments so we can begin transitioning to a state where all clients and servers support the full set of Open Payments use cases.

**Comment by sharafian** [comment]
If we wanted to we could remove the requirement for everybody to migrate their SPSP endpoints though, just at the cost of having these camel case fields.

We did intentionally choose the name destination_account over ilp_address in the past, seeing as destination_account describes what the field _is_, rather than the format of it.

While technically non-breaking right now, we'll need to manage this migration. It seems like a fairly steep price just for camel case.

**Comment by kincaidoneil** [comment]
> We did intentionally choose the name destination_account over ilp_address in the past, seeing as destination_account describes what the field is, rather than the format of it.

What about `destinationAddress`? That's what I'ved use internally since I don't feel either are sufficiently descriptive ("account" is pretty overloaded)

**Comment by sharafian** [comment]
:+1: I agree that's a better name than destination_account or ilpAddress but I'm still not bought in on the idea of migrating just to change some field names

**Comment by adrianhopebailie** [comment]
> While technically non-breaking right now, we'll need to manage this migration. It seems like a fairly steep price just for camel case.

Sure, but we're setting a standard for a much wider set of schemas so we're trying to fix this early before people start implementing invoices and mandates etc.

A compliant server will serve both Open Payments and SPSP clients but with a goal to moving SPSP clients to Open Payments over time.

> What about destinationAddress? That's what I've use internally since I don't feel either are sufficiently descriptive ("account" is pretty overloaded)

👍
