### ISSUE TITLE
docs: creating a wallet account updates (rafiki.money to wallet.interledger-test.dev)

### ISSUE THREAD

**Issue by melissahenderson** [interledger/open-payments#509]
We need to update https://openpayments.dev/snippets/before-you-begin/, as well as search for and change Rafiki Money and Rafiki Boutique references within the Open Payments docs.

We need to verify the Before you Begin steps and update as needed. We also need to replace the screenshots. 
- rafiki.money is now [wallet.interledger-test.dev](http://wallet.interledger-test.dev/)
- rafiki.boutique is now [boutique.interledger-test.dev](http://boutique.interledger-test.dev/)

A few things to keep in mind... some of these points might be appropriate for the docs while others won't be:
- If you have an old account on Rafiki.money, you must register again. You'll have to set a strong password and complete a new KYC process. Previous wallet accounts and balances will no longer be available.
- interledger-test is running on a GateHub preproduction environment which means everything should be exactly as it is in production, including the KYC process.
- The only real information you need to share during the KYC process is your email address and a phone number. Phone is required because of a text confirmation via SMS. Everything else can be fake. 
- If required to take a photo, it can be of anything, just not a blank page. Face scan still has to be done.
- Using the QR code with mobile is easier to go through KYC.
- ~~As of October 16, 2024, add smaller amounts--500 or under--for deposits. GateHub currently has a security threshold on larger sums that need manual approval.~~

And finally, depending on when we get to this issue, the points above may have changed 🙃 The Testnet team is actively working with GateHub.

**Comment by mkurapov** [comment]
> As of October 16, 2024, add smaller amounts--500 or under--for deposits. GateHub currently has a security threshold on larger sums that need manual approval.

I believe this no longer applies anymore

**Comment by melissahenderson** [comment]
Max already worked on this in PR #510. 

For https://openpayments.dev/snippets/before-you-begin/, we should review it and then add in new screenshots. We need check whether all the points covered in this issue's description are still valid and, if so, that they made it into the doc. I only did a cursory scan of the updated page. 

If the old test wallet screenshots are still in the Starlight project, we should delete them.
